
package quanlynhansu;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FormChinh extends javax.swing.JFrame {


    public FormChinh() {
        initComponents();
//        mePM.setVisible(false);
//        meLD.setVisible(false);
//        meAD.setVisible(false);

    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnTaiKhoan = new javax.swing.JMenu();
        MnItThongTin = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MnItLogout = new javax.swing.JMenuItem();
        MnNhanVien = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MnLeader = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        MnPM = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MnAdmin = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        MnItNS = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(236, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Thiết Lập Thông Tin Show lên đây.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jLabel1)
                .addContainerGap(466, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        MnTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        MnTaiKhoan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Favorites/Avartar/icons8-name-tag-50.png"))); // NOI18N
        MnTaiKhoan.setText("Tài Khoản  ");
        MnTaiKhoan.setActionCommand(" Tài Khoản  ");
        MnTaiKhoan.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        MnItThongTin.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        MnItThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Favorites/Edit/icons8-admin-settings-male-30.png"))); // NOI18N
        MnItThongTin.setText("Hồ Sơ");
        MnItThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItThongTinActionPerformed(evt);
            }
        });
        MnTaiKhoan.add(MnItThongTin);
        MnTaiKhoan.add(jSeparator1);

        MnItLogout.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        MnItLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Favorites/Edit/icons8-sign-out-30.png"))); // NOI18N
        MnItLogout.setText("Đăng Xuất");
        MnItLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItLogoutActionPerformed(evt);
            }
        });
        MnTaiKhoan.add(MnItLogout);

        jMenuBar1.add(MnTaiKhoan);

        MnNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        MnNhanVien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        MnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Favorites/Avartar/icons8-account-50.png"))); // NOI18N
        MnNhanVien.setText(" Nhân Viên  ");
        MnNhanVien.setActionCommand(" Nhân Viên  ");
        MnNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem3.setText("Tạo Công Việc");
        MnNhanVien.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem4.setText("Gửi Báo Cáo");
        MnNhanVien.add(jMenuItem4);

        jMenuBar1.add(MnNhanVien);

        MnLeader.setBackground(new java.awt.Color(255, 255, 255));
        MnLeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MnLeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Favorites/Avartar/icons8-contact-details-50.png"))); // NOI18N
        MnLeader.setText(" Leader  ");
        MnLeader.setActionCommand(" Leader  ");
        MnLeader.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem2.setText("Tạo Công Việc");
        MnLeader.add(jMenuItem2);

        jMenuItem9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem9.setText("Thêm Nhân Sự");
        MnLeader.add(jMenuItem9);

        jMenuItem6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem6.setText("Gửi Báo Cáo");
        MnLeader.add(jMenuItem6);

        jMenuBar1.add(MnLeader);

        MnPM.setBackground(new java.awt.Color(255, 255, 255));
        MnPM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MnPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Favorites/Avartar/icons8-walter-white-50.png"))); // NOI18N
        MnPM.setText(" PM  ");
        MnPM.setActionCommand(" PM  ");
        MnPM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenuItem10.setText("Thêm Nhân Sự");
        MnPM.add(jMenuItem10);

        jMenuItem11.setText("Danh Sách Dự Án");
        MnPM.add(jMenuItem11);

        jMenuItem5.setText("Gửi Báo Cáo");
        MnPM.add(jMenuItem5);

        jMenuBar1.add(MnPM);

        MnAdmin.setBackground(new java.awt.Color(255, 255, 255));
        MnAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Favorites/Avartar/icons8-vip-50.png"))); // NOI18N
        MnAdmin.setText(" Quản Trị Viên");
        MnAdmin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenu7.setText("Quản Lý Nhân Sự");
        jMenu7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        MnItNS.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        MnItNS.setText("Nhân Sự");
        MnItNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItNSActionPerformed(evt);
            }
        });
        jMenu7.add(MnItNS);

        MnAdmin.add(jMenu7);

        jMenu2.setText("Danh Sách");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem7.setText("Danh Sách Dự Án");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem15.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem15.setText("Danh Sách Nhân Sự");
        jMenu2.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem16.setText("Danh Sách Báo Cáo");
        jMenu2.add(jMenuItem16);

        MnAdmin.add(jMenu2);
        MnAdmin.add(jSeparator3);

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem1.setText("Thống kê");
        MnAdmin.add(jMenuItem1);

        jMenuBar1.add(MnAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnItThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItThongTinActionPerformed
        FormProfile frmProfile = new FormProfile();
        frmProfile.showProfile();
        frmProfile.show();
    }//GEN-LAST:event_MnItThongTinActionPerformed

    private void MnItLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItLogoutActionPerformed
            //<editor-fold defaultstate="collapsed" desc=" Xác Nhận Đóng Form "> 
            int x = JOptionPane.showConfirmDialog(this, "Xác Nhận Đăng Xuất?","Thông báo",JOptionPane.YES_NO_OPTION);
            if (x == JOptionPane.YES_OPTION) {
            Login frmlogin = new Login();
            frmlogin.setVisible(true);
            dispose();
            } 
        //</editor-fold>
    }//GEN-LAST:event_MnItLogoutActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void MnItNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItNSActionPerformed
            try {
            ChucNang cn = new ChucNang();
            if(NhanVien.getInstance().getMachucvu() > 1){
                JOptionPane.showMessageDialog(null, "Bạn không có quyền truy cập");
            }
            else {
                NhanSu ns = new NhanSu();
                dispose();
                ns.setVisible(true); // show form
                ns.model(); //lấy jtable
                ns.comboBoxModel(); // lấy combobox
                cn.shownhanvien(ns.model);  // show nhân viên vào jtable
                cn.showcombobox(ns.comboBoxModel);
                ns.disable();
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormChinh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnItNSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnAdmin;
    private javax.swing.JMenuItem MnItLogout;
    private javax.swing.JMenuItem MnItNS;
    private javax.swing.JMenuItem MnItThongTin;
    private javax.swing.JMenu MnLeader;
    private javax.swing.JMenu MnNhanVien;
    private javax.swing.JMenu MnPM;
    private javax.swing.JMenu MnTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
